# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='fn_graph',
    version='0.7.0',
    description='Manage, maintain and reuse complex function graphs without the hassle.',
    python_requires='==3.*,>=3.7.0',
    project_urls={
        "documentation": "https://fn-graph.readthedocs.io/",
        "homepage": "https://github.com/BusinessOptics/fn_graph",
        "repository": "https://github.com/BusinessOptics/fn_graph"
    },
    author='James Saunders',
    author_email='james@businessoptics.biz',
    license='MIT',
    packages=['fn_graph', 'fn_graph.examples', 'fn_graph.tests'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'graphviz==0.*,>=0.13.2', 'joblib==0.*,>=0.14.1',
        'littleutils==0.*,>=0.2.1', 'networkx==2.*,>=2.4.0',
        'typing==3.*,>=3.7.0'
    ],
    extras_require={
        "dev": [
            "black==18.*,>=18.3.0", "mkdocs==1.*,>=1.0.0",
            "pandas==0.*,>=0.25.3", "pytest==5.*,>=5.3.0",
            "recommonmark==0.*,>=0.6.0", "sphinx==2.*,>=2.2.0",
            "sphinx-rtd-theme==0.*,>=0.4.3"
        ]
    },
)
